name: Build and Test with Anaconda

on:
  push:
    branches:
      - main
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment
      run: echo "conda activate indiansignlanguage" >> $GITHUB_ENV

    - name: Install additional dependencies
      run: |
        conda activate indiansignlanguage
        pip install -r requirements.txt

    - name: Run tests
      run: |
        conda activate indiansignlanguage
        pytest
